### PR TITLE
Add functions, concurrency, wait/post (type checking is not complete)

### PR DESCRIPTION
**Pull request by leonidas1712**
- [ ] Function calls
  - [x] Parsing
  - [x] Compilation
  - [ ] Type check
 
- [ ] Function declarations    
  - [x] Parsing
  - [x]  Compilation
  - [ ] Type check

- [x] Add spawn
  -  No type annotation/proper type checking but I did make a Type::ThreadId
- [x] Add join - for now just ```join <symbol>``` , no fancy expr allowed
- [x] Add wait and post 
- [x] Add yield
- [x] Add string literals
- [x] Update examples

See examples for function declarations. With type checking on, the following is currently enforced:

1. Function calls (builtin or user) check for number/ types of arguments match
2. All function declaration parameters must have a type annotation. Return type is optional, and if not present is taken as unit
3. Function calls are typed, e.g ```let x : bool = func();``` where func returns int will fail type checking

However, I have not added type checking of the function body yet and some other features related to type checking. Will do this in another PR after presentation.

This PR also adds syntax/compilation for spawn, join, wait, post, yield and string literals. 

All the examples should now be functional, except for garbage-collection-02 and higher-order-fn-01 as support for function types in annotations is not added yet. These are functional when compiling / running untyped.

### CODE REVIEW

**Comment by leonidas1712** [comment]
Screenshot 2024-04-17 at 12 44 51 AM

Screenshot 2024-04-17 at 12 53 53 AM

There might be a bug with the VM call microcode.

By default, the HW compiler will compile arguments left to right so e.g for math_pow(2,3) it pushes LD math_pow, LDC 2, LDC 3.

But the HW’s CALL takes the arguments and puts them at the end (hence i = arity-1 at the start) then decrements the index, so the args passed are in the original order i.e [2,3] again

However with the rst VM, it seems that since the args are added as they are popped, the order is actually reversed so it ends up calling the function with reversed arguments. 

If you don’t want to reverse the args after adding, you could use VecDeque to to add the arguments to the front instead

@ForAeons

**Comment by wxiaoyun** [comment]
> Screenshot 2024-04-17 at 12 44 51 AM Screenshot 2024-04-17 at 12 53 53 AM
> 
> There might be a bug with the VM call microcode.
> 
> By default, the HW compiler will compile arguments left to right so e.g for math_pow(2,3) it pushes LD math_pow, LDC 2, LDC 3.
> 
> But the HW’s CALL takes the arguments and puts them at the end (hence i = arity-1 at the start) then decrements the index, so the args passed are in the original order i.e [2,3] again
> 
> However with the rst VM, it seems that since the args are added as they are popped, the order is actually reversed so it ends up calling the function with reversed arguments.
> 
> If you don’t want to reverse the args after adding, you could use VecDeque to to add the arguments to the front instead
> 
> @ForAeons

Will fix this and submit a PR https://github.com/crabscript/rustscript/pull/52
Whats HW?

**Comment by leonidas1712** [comment]
oh right HW is "homework"

**Comment by wxiaoyun** [comment]
Hey man, I found a bug with extending the environment that prevents higher order function call. It is fixed in https://github.com/crabscript/rustscript/pull/50

**Pull request merged**
